name: 'Upload Android Screenshots'
description: 'Upload the Android Application screenshots/images to Google Play'
inputs:
  serviceAccountJson:
    description: "The service account json private key file to authorize the upload request"
    required: false
  serviceAccountJsonPlainText:
    description: "The raw json text of the service account private key to authorize the upload request"
    required: false
  packageName:
    description: "Package name of the app"
    required: true
  language:
    description: "Language localization code (BCP-47 language tag)"
    required: true
  imageType:
    description: "Type of image to upload to Google Play"
    required: true
  imageFiles: 
    description: "Files to upload as a 'glob' string"
    required: true
  changesNotSentForReview:
    description: "Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console"
    required: false 
    default: 'false'
runs:
  using: 'node20'
  main: 'lib/index.js'
